<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>
    <Company>PrettyDesk</Company>
    <Product>PrettyDesk</Product>
    <Copyright>PrettyDesk contributors</Copyright>
  </PropertyGroup>
</Project>
