"""Render ``art/PROMPTS.md``: one copy-paste friendly section per pack (ART_DIRECTION.md section 6)."""

from __future__ import annotations

from .packs import RAW_SUFFIX, Pack, Wallpaper

HEADER = """# PrettyDesk art prompts

> Generated by `assetpipe prompts` from `art/prompts/*.yaml`. **Do not edit by hand.**

## How to use

1. Start a **new ChatGPT chat for each pack**. Paste the pack's **Style bible** first, then each wallpaper's prompts in order.
2. **L, the landscape master.** Paste the *Landscape* prompt and ask for **16:9 landscape at the highest resolution available**.
   Download the full-resolution PNG with ChatGPT's download button, not a screenshot.
3. **U, the ultrawide master.** In the same chat, with that image selected, paste the *Ultrawide* prompt. It extends the image to a
   3:1 panorama. If 3:1 is not possible, accept 21:9 or wider; the pipeline adapts.
4. **P, the portrait master** (only where a *Portrait* prompt exists). Paste it with the L image attached.
5. Save as `art/raw/{packId}/{wallpaperId}_L.png`, `_U.png`, `_P.png`, then run `assetpipe status`, `assetpipe build --pack ID`,
   `assetpipe review --pack ID`.

**Review checklist** (every wallpaper):

- [ ] No text, letters, glyph-like squiggles, logos or watermarks anywhere (zoom to 100%)
- [ ] No warped geometry, melted objects, broken perspective, or duplicate or extra limbs
- [ ] The ultrawide extension has no visible seam, repeated objects or lighting mismatch
- [ ] The left 15% and bottom 8% are calm; the focal point sits where the YAML says
- [ ] Gradients and darks are smooth at 100% zoom (raise the screen brightness to check for banding)
- [ ] It still reads well at thumbnail size
- [ ] It follows the pack's art mode: generic inspiration, or recognizable approved fan-art
  subjects in a new composition; no implied official endorsement
- [ ] It feels like the rest of its pack

If a check fails, regenerate and note it under `reviewNotes`. If it passes, set `approved: true` and adjust `focal` if the subject landed elsewhere.
"""


def _block(text: str) -> str:
    return "```text\n" + text.strip() + "\n```\n"


def _wallpaper(pack: Pack, wp: Wallpaper) -> str:
    focal = f"focal {wp.focal_x:.2f}, {wp.focal_y:.2f}"
    meta = f"{wp.role} · {wp.tone} · setup: {', '.join(wp.setup_match)} · {focal} · upscaler: {wp.upscaler} · grain {wp.grain:g}"
    if wp.starter:
        meta += " · **starter**"
    lines = [f"#### {wp.title} (`{wp.id}`)", "", meta, ""]
    for kind, label in (("landscape", "Landscape (L)"), ("ultrawide", "Ultrawide (U)"), ("portrait", "Portrait (P)")):
        text = wp.prompts.get(kind)
        if text:
            lines += [f"**{label}**: save as `art/raw/{pack.id}/{wp.id}_{RAW_SUFFIX[kind]}.png`", "", _block(text)]
    return "\n".join(lines)


def render_pack(pack: Pack) -> str:
    lines = [f"### {pack.title} (`{pack.id}`)", ""]
    insp = pack.inspiration
    if isinstance(insp, dict):
        lines += [
            f"- **Genre:** {insp.get('genre', '')}",
            f"- **Setting:** {insp.get('setting', '')}",
            f"- **Palette:** {', '.join(insp.get('palette', []))}",
            f"- **Motifs:** {', '.join(insp.get('motifs', []))}",
            f"- **Avoid:** {', '.join(insp.get('avoid', []))}",
            "",
        ]
    if pack.art_mode == "named-fan-art":
        lines += [f"**Named fan art:** {', '.join(pack.named_subjects)}. Original compositions; verify car geometry, no HUD/text/logos, safe crops and distribution rights before release.", ""]
    lines += ["**Style bible** (paste first):", "", _block(pack.style_bible)]
    lines += [_wallpaper(pack, wp) for wp in pack.wallpapers]
    return "\n".join(lines)


def render(packs: list[Pack]) -> str:
    defaults = [p for p in packs if p.kind == "default"]
    games = [p for p in packs if p.kind == "game"]
    total = sum(len(p.wallpapers) for p in packs)
    parts = [HEADER, f"**{len(packs)} packs · {total} wallpapers** ({len(defaults)} default collections, {len(games)} game packs)\n"]
    parts.append("## Contents\n")
    for group, title in ((defaults, "Default collections"), (games, "Game packs")):
        if group:
            parts.append(f"**{title}**\n")
            parts += [f"- `{p.id}`: {p.title} ({len(p.wallpapers)})" for p in group]
            parts.append("")
    if defaults:
        parts.append("## Default collections\n")
        parts += [render_pack(p) for p in defaults]
    if games:
        parts.append("## Game packs\n")
        parts += [render_pack(p) for p in games]
    return "\n".join(parts).rstrip() + "\n"
