// <auto-generated>Generated by tools/strings.py from Strings.resx. Do not edit.</auto-generated>
#nullable enable
using System.Globalization;
using System.Resources;

namespace PrettyDesk.Presentation.Resources;

/// <summary>Typed access to <c>Strings.resx</c>. Every user-facing string lives there (NFR-11).</summary>
public static class Strings
{
    private static readonly ResourceManager Manager = new("PrettyDesk.Presentation.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>Overrides the culture for tests and previews; null uses the current UI culture.</summary>
    public static CultureInfo? Culture { get; set; }

    public static string Get(string key) => Manager.GetString(key, Culture) ?? key;

    public static string Format(string template, params object?[] args) =>
        string.Format(Culture ?? CultureInfo.CurrentUICulture, template, args);

    /// <summary>Every key in the resource file, for drift checks.</summary>
    public static IReadOnlyList<string> AllKeys { get; } =
    [
        "Bytes_B",
        "Bytes_GB",
        "Bytes_KB",
        "Bytes_MB",
        "Common_Add",
        "Common_AppName",
        "Common_Back",
        "Common_Browse",
        "Common_Cancel",
        "Common_Close",
        "Common_Done",
        "Common_Finish",
        "Common_Loading",
        "Common_Next",
        "Common_OK",
        "Common_Off",
        "Common_On",
        "Common_Remove",
        "Common_Retry",
        "Common_Save",
        "Nav_About",
        "Nav_Defaults",
        "Nav_Home",
        "Nav_Library",
        "Nav_Settings",
        "Status_ApplyFailed",
        "Status_Blocked",
        "Status_BlockedDetail",
        "Status_DefaultFixed",
        "Status_DefaultNextChange",
        "Status_DefaultNoContent",
        "Status_DefaultNoContentDetail",
        "Status_DefaultRotating",
        "Status_GameEnded",
        "Status_GameLoading",
        "Status_GameLoadingDetail",
        "Status_Paused",
        "Status_PausedIndefinite",
        "Status_PausedUntil",
        "Status_Playing",
        "Status_PlayingDetailPosition",
        "Status_Preview",
        "Status_PreviewDetail",
        "Status_Starting",
        "Time_Days",
        "Time_Hours",
        "Time_HoursMinutes",
        "Time_Minutes",
        "Time_OneDay",
        "Time_UnderMinute",
    ];

    /// <summary>{0} B</summary>
    public static string Bytes_B => Get("Bytes_B");

    /// <summary>{0} GB</summary>
    public static string Bytes_GB => Get("Bytes_GB");

    /// <summary>{0} KB</summary>
    public static string Bytes_KB => Get("Bytes_KB");

    /// <summary>{0} MB</summary>
    public static string Bytes_MB => Get("Bytes_MB");

    /// <summary>Add</summary>
    public static string Common_Add => Get("Common_Add");

    /// <summary>PrettyDesk</summary>
    public static string Common_AppName => Get("Common_AppName");

    /// <summary>Back</summary>
    public static string Common_Back => Get("Common_Back");

    /// <summary>Browse…</summary>
    public static string Common_Browse => Get("Common_Browse");

    /// <summary>Cancel</summary>
    public static string Common_Cancel => Get("Common_Cancel");

    /// <summary>Close</summary>
    public static string Common_Close => Get("Common_Close");

    /// <summary>Done</summary>
    public static string Common_Done => Get("Common_Done");

    /// <summary>Finish</summary>
    public static string Common_Finish => Get("Common_Finish");

    /// <summary>Loading…</summary>
    public static string Common_Loading => Get("Common_Loading");

    /// <summary>Next</summary>
    public static string Common_Next => Get("Common_Next");

    /// <summary>OK</summary>
    public static string Common_OK => Get("Common_OK");

    /// <summary>Off</summary>
    public static string Common_Off => Get("Common_Off");

    /// <summary>On</summary>
    public static string Common_On => Get("Common_On");

    /// <summary>Remove</summary>
    public static string Common_Remove => Get("Common_Remove");

    /// <summary>Try again</summary>
    public static string Common_Retry => Get("Common_Retry");

    /// <summary>Save</summary>
    public static string Common_Save => Get("Common_Save");

    /// <summary>About</summary>
    public static string Nav_About => Get("Nav_About");

    /// <summary>Defaults</summary>
    public static string Nav_Defaults => Get("Nav_Defaults");

    /// <summary>Home</summary>
    public static string Nav_Home => Get("Nav_Home");

    /// <summary>Library</summary>
    public static string Nav_Library => Get("Nav_Library");

    /// <summary>Settings</summary>
    public static string Nav_Settings => Get("Nav_Settings");

    /// <summary>Couldn't change the wallpaper. Trying again…</summary>
    public static string Status_ApplyFailed => Get("Status_ApplyFailed");

    /// <summary>Your organization manages your wallpaper</summary>
    public static string Status_Blocked => Get("Status_Blocked");

    /// <summary>PrettyDesk can't change it on this PC.</summary>
    public static string Status_BlockedDetail => Get("Status_BlockedDetail");

    /// <summary>Default · {0}</summary>
    public static string Status_DefaultFixed => Get("Status_DefaultFixed");

    /// <summary>Next change {0}</summary>
    public static string Status_DefaultNextChange => Get("Status_DefaultNextChange");

    /// <summary>No wallpapers are available yet</summary>
    public static string Status_DefaultNoContent => Get("Status_DefaultNoContent");

    /// <summary>Pick a collection in Defaults, or add your own images.</summary>
    public static string Status_DefaultNoContentDetail => Get("Status_DefaultNoContentDetail");

    /// <summary>Default · {0} (rotating)</summary>
    public static string Status_DefaultRotating => Get("Status_DefaultRotating");

    /// <summary>Returning to your default wallpaper soon</summary>
    public static string Status_GameEnded => Get("Status_GameEnded");

    /// <summary>Getting {0} wallpapers…</summary>
    public static string Status_GameLoading => Get("Status_GameLoading");

    /// <summary>Your current wallpaper stays until they're ready.</summary>
    public static string Status_GameLoadingDetail => Get("Status_GameLoadingDetail");

    /// <summary>Paused</summary>
    public static string Status_Paused => Get("Status_Paused");

    /// <summary>Paused until you resume</summary>
    public static string Status_PausedIndefinite => Get("Status_PausedIndefinite");

    /// <summary>Paused until {0}</summary>
    public static string Status_PausedUntil => Get("Status_PausedUntil");

    /// <summary>Playing: {0}</summary>
    public static string Status_Playing => Get("Status_Playing");

    /// <summary>Wallpaper {0} of {1}</summary>
    public static string Status_PlayingDetailPosition => Get("Status_PlayingDetailPosition");

    /// <summary>Previewing a wallpaper</summary>
    public static string Status_Preview => Get("Status_Preview");

    /// <summary>It goes back to normal in a few seconds.</summary>
    public static string Status_PreviewDetail => Get("Status_PreviewDetail");

    /// <summary>Starting…</summary>
    public static string Status_Starting => Get("Status_Starting");

    /// <summary>in {0} days</summary>
    public static string Time_Days => Get("Time_Days");

    /// <summary>in {0} h</summary>
    public static string Time_Hours => Get("Time_Hours");

    /// <summary>in {0} h {1} min</summary>
    public static string Time_HoursMinutes => Get("Time_HoursMinutes");

    /// <summary>in {0} min</summary>
    public static string Time_Minutes => Get("Time_Minutes");

    /// <summary>in 1 day</summary>
    public static string Time_OneDay => Get("Time_OneDay");

    /// <summary>in under a minute</summary>
    public static string Time_UnderMinute => Get("Time_UnderMinute");
}
