// <auto-generated>Generated by tools/strings.py from Strings.resx. Do not edit.</auto-generated>
#nullable enable
using System.Globalization;
using System.Resources;

namespace PrettyDesk.Presentation.Resources;

/// <summary>Typed access to <c>Strings.resx</c>. Every user-facing string lives there (NFR-11).</summary>
public static class Strings
{
    private static readonly ResourceManager Manager = new("PrettyDesk.Presentation.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>Overrides the culture for tests and previews; null uses the current UI culture.</summary>
    public static CultureInfo? Culture { get; set; }

    public static string Get(string key) => Manager.GetString(key, Culture) ?? key;

    public static string Format(string template, params object?[] args) =>
        string.Format(Culture ?? CultureInfo.CurrentUICulture, template, args);

    /// <summary>Every key in the resource file, for drift checks.</summary>
    public static IReadOnlyList<string> AllKeys { get; } =
    [
        "About_CheckUpdates",
        "About_Disclaimer",
        "About_Licenses",
        "About_LicensesHelp",
        "About_PrivacyBody",
        "About_PrivacyLink",
        "About_PrivacyTitle",
        "About_ProjectPage",
        "About_ReportIssue",
        "About_Title",
        "About_UpdateAvailable",
        "About_UpdateChecking",
        "About_UpdateDownloading",
        "About_UpdateFailed",
        "About_UpdateIdle",
        "About_UpdateNotSupported",
        "About_UpdateReady",
        "About_UpdateRestart",
        "About_UpdateUpToDate",
        "About_Version",
        "Add_AlreadyCovered",
        "Add_BrowseExe",
        "Add_DisplayName",
        "Add_Exe",
        "Add_ImportMine",
        "Add_ImportSkipped",
        "Add_Intro",
        "Add_LauncherBlocked",
        "Add_NeedName",
        "Add_NeedWallpaper",
        "Add_NoExe",
        "Add_PickFromCollections",
        "Add_Refresh",
        "Add_Running",
        "Add_RunningEmpty",
        "Add_Save",
        "Add_SaveFailed",
        "Add_Saved",
        "Add_Search",
        "Add_Title",
        "Add_Wallpapers",
        "Add_WallpapersHelp",
        "Banner_Dismiss",
        "Banner_LivelyBody",
        "Banner_LivelyTitle",
        "Banner_PolicyBody",
        "Banner_PolicyTitle",
        "Banner_SpotlightBody",
        "Banner_SpotlightTitle",
        "Banner_WallpaperEngineBody",
        "Banner_WallpaperEngineTitle",
        "Bytes_B",
        "Bytes_GB",
        "Bytes_KB",
        "Bytes_MB",
        "Common_Add",
        "Common_AppName",
        "Common_Back",
        "Common_Browse",
        "Common_Cancel",
        "Common_Close",
        "Common_Done",
        "Common_Finish",
        "Common_Loading",
        "Common_Next",
        "Common_OK",
        "Common_Off",
        "Common_On",
        "Common_Remove",
        "Common_Retry",
        "Common_Save",
        "Defaults_AddImages",
        "Defaults_Battery",
        "Defaults_BatteryHelp",
        "Defaults_CollectionCount",
        "Defaults_CollectionNotDownloaded",
        "Defaults_CollectionToggle",
        "Defaults_Collections",
        "Defaults_CollectionsEmptyBody",
        "Defaults_CollectionsEmptyTitle",
        "Defaults_FixedHelp",
        "Defaults_FixedPick",
        "Defaults_FollowTheme",
        "Defaults_FollowThemeHelp",
        "Defaults_ImageWarning",
        "Defaults_ImportDone",
        "Defaults_ImportFailed",
        "Defaults_ImportSkipped",
        "Defaults_Interval",
        "Defaults_IntervalCustomHelp",
        "Defaults_IntervalCustomMinutes",
        "Defaults_Intro",
        "Defaults_KeepOne",
        "Defaults_Mode",
        "Defaults_ModeFixed",
        "Defaults_ModeRotate",
        "Defaults_MyImages",
        "Defaults_MyImagesEmpty",
        "Defaults_MyImagesHelp",
        "Defaults_NoFixedYet",
        "Defaults_Order",
        "Defaults_RemoveImage",
        "Defaults_SetupStyle",
        "Defaults_SetupStyleHelp",
        "Defaults_Title",
        "Defaults_UseMyImages",
        "Error_StartupBody",
        "Error_StartupTitle",
        "Game_AddMyImages",
        "Game_AddWallpapers",
        "Game_Back",
        "Game_DetectionExe",
        "Game_DetectionHelp",
        "Game_DetectionNone",
        "Game_DetectionSteam",
        "Game_DetectionTitle",
        "Game_Download",
        "Game_DownloadFailed",
        "Game_Downloading",
        "Game_EditExe",
        "Game_EditExeHelp",
        "Game_Enabled",
        "Game_ExeInvalid",
        "Game_Favorite",
        "Game_Include",
        "Game_KeepOne",
        "Game_Mode",
        "Game_ModeFixed",
        "Game_ModeRotate",
        "Game_NoWallpapers",
        "Game_NotDownloaded",
        "Game_Order",
        "Game_OrderSequential",
        "Game_OrderShuffle",
        "Game_PackUnavailable",
        "Game_Prefetch",
        "Game_PrefetchHelp",
        "Game_Preview",
        "Game_PreviewHelp",
        "Game_RemoveGame",
        "Game_RemoveMessage",
        "Game_RemoveTitle",
        "Game_Rotation",
        "Game_RotationHelp",
        "Game_Suggest",
        "Game_SuggestHelp",
        "Game_Unfavorite",
        "Game_WallpapersTitle",
        "Home_DisplayLabel",
        "Home_GlassAction",
        "Home_GlassDetail",
        "Home_GlassTitle",
        "Home_NextWallpaper",
        "Home_NoMonitors",
        "Home_NoMonitorsDetail",
        "Home_NoWallpaperYet",
        "Home_Pause",
        "Home_PauseOneHour",
        "Home_PauseUntilResumed",
        "Home_PreviewLabel",
        "Home_PrimaryDisplay",
        "Home_Resume",
        "Home_Title",
        "Interval_Custom",
        "Interval_Daily",
        "Interval_Days",
        "Interval_Hour",
        "Interval_Hours",
        "Interval_Minutes",
        "Interval_Never",
        "Interval_Session",
        "Interval_Unlock",
        "Library_AddGame",
        "Library_ChipCustom",
        "Library_ChipDownloading",
        "Library_ChipFailed",
        "Library_ChipInstalled",
        "Library_ChipNotDownloaded",
        "Library_ChipReady",
        "Library_ChipUnavailable",
        "Library_DisclaimerNote",
        "Library_EmptyCatalogBody",
        "Library_EmptyCatalogTitle",
        "Library_EmptyEnabledBody",
        "Library_EmptyEnabledTitle",
        "Library_EmptyInstalledBody",
        "Library_EmptyInstalledTitle",
        "Library_EmptySearchBody",
        "Library_EmptySearchTitle",
        "Library_FilterAll",
        "Library_FilterEnabled",
        "Library_FilterInstalled",
        "Library_GameToggle",
        "Library_Search",
        "Library_Title",
        "Nav_About",
        "Nav_Defaults",
        "Nav_Home",
        "Nav_Library",
        "Nav_Settings",
        "Notify_DownloadFailedBody",
        "Notify_DownloadFailedTitle",
        "Notify_SettingsRecoveredBody",
        "Notify_SettingsRecoveredTitle",
        "Notify_UnknownGameAction",
        "Notify_UnknownGameBody",
        "Notify_UnknownGameTitle",
        "Notify_UpdateBody",
        "Notify_UpdateTitle",
        "Onboard_AlreadyIncluded",
        "Onboard_BackgroundHelp",
        "Onboard_DisplayFitHelp",
        "Onboard_DisplayGroup",
        "Onboard_DisplaysMissing",
        "Onboard_DoneBody",
        "Onboard_DoneTip",
        "Onboard_DoneTitle",
        "Onboard_DownloadBackground",
        "Onboard_DownloadProgress",
        "Onboard_DownloadRetry",
        "Onboard_DownloadSelected",
        "Onboard_DownloadTotal",
        "Onboard_DownloadUnavailable",
        "Onboard_Failed",
        "Onboard_FormatFallback",
        "Onboard_FormatLandscape",
        "Onboard_FormatPortrait",
        "Onboard_FormatSuperwide",
        "Onboard_FormatUltrawide",
        "Onboard_GamesBody",
        "Onboard_GamesEmptyBody",
        "Onboard_GamesEmptyTitle",
        "Onboard_GamesLoading",
        "Onboard_GamesTitle",
        "Onboard_Megabytes",
        "Onboard_ModeBody",
        "Onboard_ModeFixed",
        "Onboard_ModeInterval",
        "Onboard_ModeRotate",
        "Onboard_ModeTitle",
        "Onboard_NoDownloadsNeeded",
        "Onboard_NoGamePacks",
        "Onboard_NoMatchingArt",
        "Onboard_PackDownloadSize",
        "Onboard_ScanFailed",
        "Onboard_ScanRetry",
        "Onboard_SpotlightNote",
        "Onboard_Start",
        "Onboard_StartupBody",
        "Onboard_StartupTitle",
        "Onboard_StartupToggle",
        "Onboard_StepOf",
        "Onboard_StyleBody",
        "Onboard_StyleCleanWhite",
        "Onboard_StyleCleanWhiteHelp",
        "Onboard_StyleMatteBlack",
        "Onboard_StyleMatteBlackHelp",
        "Onboard_StylePastel",
        "Onboard_StylePastelHelp",
        "Onboard_StyleRgb",
        "Onboard_StyleRgbHelp",
        "Onboard_StyleSurprise",
        "Onboard_StyleSurpriseHelp",
        "Onboard_StyleTitle",
        "Onboard_StyleWarmWood",
        "Onboard_StyleWarmWoodHelp",
        "Onboard_WallpapersBody",
        "Onboard_WallpapersTitle",
        "Onboard_WelcomeBody",
        "Onboard_WelcomePoint1",
        "Onboard_WelcomePoint2",
        "Onboard_WelcomePoint3",
        "Onboard_WelcomeTitle",
        "Picker_Confirm",
        "Picker_Empty",
        "Picker_GroupMine",
        "Picker_Search",
        "Picker_Selected",
        "Picker_Title",
        "Settings_Advanced",
        "Settings_AppTheme",
        "Settings_AppThemeHelp",
        "Settings_BetaUpdates",
        "Settings_BetaUpdatesHelp",
        "Settings_ClearDownloads",
        "Settings_ClearDownloadsDone",
        "Settings_ClearDownloadsFailed",
        "Settings_ClearDownloadsMessage",
        "Settings_ClearDownloadsTitle",
        "Settings_ClockMonitor",
        "Settings_DesktopClock",
        "Settings_DesktopClockHelp",
        "Settings_DetectDelay",
        "Settings_DetectDelayHelp",
        "Settings_DetectGames",
        "Settings_DetectGamesHelp",
        "Settings_Detection",
        "Settings_DetectionLog",
        "Settings_DetectionLogClear",
        "Settings_DetectionLogEmpty",
        "Settings_DetectionLogHelp",
        "Settings_DetectionLogLine",
        "Settings_DetectionLogMatched",
        "Settings_DetectionLogNoForeground",
        "Settings_DetectionLogNoMatch",
        "Settings_DetectionLogPause",
        "Settings_DetectionLogResume",
        "Settings_ExitGrace",
        "Settings_ExitGraceHelp",
        "Settings_ExportDiagnostics",
        "Settings_ExportDiagnosticsHelp",
        "Settings_ExportDone",
        "Settings_ExportFailed",
        "Settings_GameOnSecondaryOnly",
        "Settings_GameOnSecondaryOnlyHelp",
        "Settings_General",
        "Settings_MediaUnavailable",
        "Settings_MonitorDifferent",
        "Settings_MonitorMode",
        "Settings_MonitorSame",
        "Settings_Monitors",
        "Settings_NextTrack",
        "Settings_Notifications",
        "Settings_NotifyDownloadErrors",
        "Settings_NotifyHelp",
        "Settings_NotifyUnknownGames",
        "Settings_NotifyUpdates",
        "Settings_NowPlaying",
        "Settings_OpenColors",
        "Settings_OpenLogs",
        "Settings_PlayPause",
        "Settings_PollSeconds",
        "Settings_PollSecondsValue",
        "Settings_PrefetchGames",
        "Settings_PrefetchGamesHelp",
        "Settings_ResetApp",
        "Settings_ResetAppHelp",
        "Settings_ResetFailed",
        "Settings_ResetKeepImages",
        "Settings_ResetMessage",
        "Settings_ResetRemoveImages",
        "Settings_ResetTitle",
        "Settings_Restore",
        "Settings_RestoreDone",
        "Settings_RestoreFailed",
        "Settings_RestoreMessage",
        "Settings_RestoreNothing",
        "Settings_RestoreOnExit",
        "Settings_RestoreOnExitHelp",
        "Settings_RestoreOriginal",
        "Settings_RestoreOriginalHelp",
        "Settings_RestoreTitle",
        "Settings_Restoring",
        "Settings_ShowInFolder",
        "Settings_StartWithWindows",
        "Settings_StartWithWindowsHelp",
        "Settings_Storage",
        "Settings_StorageCap",
        "Settings_StorageCapValue",
        "Settings_StorageUsed",
        "Settings_Title",
        "Settings_UnknownGameHints",
        "Settings_UnknownGameHintsHelp",
        "Settings_Visualizer",
        "Settings_VisualizerHelp",
        "Settings_WindowsColors",
        "Settings_WindowsColorsHelp",
        "Settings_Working",
        "Shell_NavLabel",
        "Status_ApplyFailed",
        "Status_Blocked",
        "Status_BlockedDetail",
        "Status_DefaultFixed",
        "Status_DefaultNextChange",
        "Status_DefaultNoContent",
        "Status_DefaultNoContentDetail",
        "Status_DefaultRotating",
        "Status_GameEnded",
        "Status_GameLoading",
        "Status_GameLoadingDetail",
        "Status_Paused",
        "Status_PausedIndefinite",
        "Status_PausedUntil",
        "Status_Playing",
        "Status_PlayingDetailPosition",
        "Status_Preview",
        "Status_PreviewDetail",
        "Status_Starting",
        "Time_Days",
        "Time_Hours",
        "Time_HoursMinutes",
        "Time_Minutes",
        "Time_OneDay",
        "Time_UnderMinute",
        "Tray_FirstHideBody",
        "Tray_FirstHideTitle",
        "Tray_Next",
        "Tray_Open",
        "Tray_Pause",
        "Tray_PauseOneHour",
        "Tray_PauseUntilResumed",
        "Tray_Quit",
        "Tray_Resume",
        "Tray_Tooltip",
        "Uninstall_KeepDataBody",
        "Uninstall_KeepDataTitle",
        "Widget_DefaultOutput",
        "Widget_MediaUnavailable",
        "Widget_NothingPlaying",
        "Widget_PlaybackUnavailable",
        "Widget_VisualizerPaused",
    ];

    /// <summary>Check for updates</summary>
    public static string About_CheckUpdates => Get("About_CheckUpdates");

    /// <summary>PrettyDesk is an independent fan project and is not affiliated with or endorsed by any game publisher. All wallpapers are original artwork inspired by games, never copies of official art.</summary>
    public static string About_Disclaimer => Get("About_Disclaimer");

    /// <summary>Open-source licenses</summary>
    public static string About_Licenses => Get("About_Licenses");

    /// <summary>PrettyDesk is built with these open-source components.</summary>
    public static string About_LicensesHelp => Get("About_LicensesHelp");

    /// <summary>No telemetry. No accounts. PrettyDesk only contacts its own content server to download wallpapers and updates, and your list of running programs never leaves your PC.</summary>
    public static string About_PrivacyBody => Get("About_PrivacyBody");

    /// <summary>Privacy details</summary>
    public static string About_PrivacyLink => Get("About_PrivacyLink");

    /// <summary>Privacy</summary>
    public static string About_PrivacyTitle => Get("About_PrivacyTitle");

    /// <summary>Project page</summary>
    public static string About_ProjectPage => Get("About_ProjectPage");

    /// <summary>Report a problem</summary>
    public static string About_ReportIssue => Get("About_ReportIssue");

    /// <summary>About PrettyDesk</summary>
    public static string About_Title => Get("About_Title");

    /// <summary>Version {0} is available.</summary>
    public static string About_UpdateAvailable => Get("About_UpdateAvailable");

    /// <summary>Checking for updates…</summary>
    public static string About_UpdateChecking => Get("About_UpdateChecking");

    /// <summary>Downloading version {0}… {1}%</summary>
    public static string About_UpdateDownloading => Get("About_UpdateDownloading");

    /// <summary>Couldn't check for updates. Check your connection and try again.</summary>
    public static string About_UpdateFailed => Get("About_UpdateFailed");

    /// <summary>Check whether a newer version is available.</summary>
    public static string About_UpdateIdle => Get("About_UpdateIdle");

    /// <summary>This copy of PrettyDesk can't update itself. Download the newest installer from the project page.</summary>
    public static string About_UpdateNotSupported => Get("About_UpdateNotSupported");

    /// <summary>Version {0} is ready to install.</summary>
    public static string About_UpdateReady => Get("About_UpdateReady");

    /// <summary>Restart to update</summary>
    public static string About_UpdateRestart => Get("About_UpdateRestart");

    /// <summary>You're up to date.</summary>
    public static string About_UpdateUpToDate => Get("About_UpdateUpToDate");

    /// <summary>Version {0}</summary>
    public static string About_Version => Get("About_Version");

    /// <summary>{0} is already set up as {1}.</summary>
    public static string Add_AlreadyCovered => Get("Add_AlreadyCovered");

    /// <summary>Browse for program…</summary>
    public static string Add_BrowseExe => Get("Add_BrowseExe");

    /// <summary>Name</summary>
    public static string Add_DisplayName => Get("Add_DisplayName");

    /// <summary>Program</summary>
    public static string Add_Exe => Get("Add_Exe");

    /// <summary>Add my images…</summary>
    public static string Add_ImportMine => Get("Add_ImportMine");

    /// <summary>{0} image(s) couldn't be added: {1}</summary>
    public static string Add_ImportSkipped => Get("Add_ImportSkipped");

    /// <summary>Pick the game from your running apps, or browse to its program file.</summary>
    public static string Add_Intro => Get("Add_Intro");

    /// <summary>{0} is a launcher or helper, not a game, so PrettyDesk can't use it.</summary>
    public static string Add_LauncherBlocked => Get("Add_LauncherBlocked");

    /// <summary>Give the game a name.</summary>
    public static string Add_NeedName => Get("Add_NeedName");

    /// <summary>Choose at least one wallpaper.</summary>
    public static string Add_NeedWallpaper => Get("Add_NeedWallpaper");

    /// <summary>Choose a program first.</summary>
    public static string Add_NoExe => Get("Add_NoExe");

    /// <summary>Choose from collections…</summary>
    public static string Add_PickFromCollections => Get("Add_PickFromCollections");

    /// <summary>Refresh</summary>
    public static string Add_Refresh => Get("Add_Refresh");

    /// <summary>Running apps</summary>
    public static string Add_Running => Get("Add_Running");

    /// <summary>No apps with a window were found. Start your game, then press Refresh.</summary>
    public static string Add_RunningEmpty => Get("Add_RunningEmpty");

    /// <summary>Add game</summary>
    public static string Add_Save => Get("Add_Save");

    /// <summary>Couldn't add the game. Try again.</summary>
    public static string Add_SaveFailed => Get("Add_SaveFailed");

    /// <summary>{0} was added.</summary>
    public static string Add_Saved => Get("Add_Saved");

    /// <summary>Search running apps</summary>
    public static string Add_Search => Get("Add_Search");

    /// <summary>Add a game</summary>
    public static string Add_Title => Get("Add_Title");

    /// <summary>Wallpapers for this game</summary>
    public static string Add_Wallpapers => Get("Add_Wallpapers");

    /// <summary>Choose at least one. They can come from your own images or from any collection.</summary>
    public static string Add_WallpapersHelp => Get("Add_WallpapersHelp");

    /// <summary>Dismiss</summary>
    public static string Banner_Dismiss => Get("Banner_Dismiss");

    /// <summary>It draws over your desktop, so PrettyDesk's wallpapers won't be visible while it's active. Pause or close Lively to see them.</summary>
    public static string Banner_LivelyBody => Get("Banner_LivelyBody");

    /// <summary>Lively Wallpaper is running</summary>
    public static string Banner_LivelyTitle => Get("Banner_LivelyTitle");

    /// <summary>Windows is set up so wallpapers can't be changed here, so PrettyDesk is paused. Ask your IT admin if you need this changed.</summary>
    public static string Banner_PolicyBody => Get("Banner_PolicyBody");

    /// <summary>Your organization manages your wallpaper</summary>
    public static string Banner_PolicyTitle => Get("Banner_PolicyTitle");

    /// <summary>Slideshow sources and timing are backed up and restored. Windows Spotlight cannot be resumed automatically, so PrettyDesk leaves it unchanged. Switch Windows Background to Picture or Slideshow to use PrettyDesk.</summary>
    public static string Banner_SpotlightBody => Get("Banner_SpotlightBody");

    /// <summary>Windows Spotlight or a slideshow is your background</summary>
    public static string Banner_SpotlightTitle => Get("Banner_SpotlightTitle");

    /// <summary>It draws over your desktop, so PrettyDesk's wallpapers won't be visible while it's active. Pause or close Wallpaper Engine to see them.</summary>
    public static string Banner_WallpaperEngineBody => Get("Banner_WallpaperEngineBody");

    /// <summary>Wallpaper Engine is running</summary>
    public static string Banner_WallpaperEngineTitle => Get("Banner_WallpaperEngineTitle");

    /// <summary>{0} B</summary>
    public static string Bytes_B => Get("Bytes_B");

    /// <summary>{0} GB</summary>
    public static string Bytes_GB => Get("Bytes_GB");

    /// <summary>{0} KB</summary>
    public static string Bytes_KB => Get("Bytes_KB");

    /// <summary>{0} MB</summary>
    public static string Bytes_MB => Get("Bytes_MB");

    /// <summary>Add</summary>
    public static string Common_Add => Get("Common_Add");

    /// <summary>PrettyDesk</summary>
    public static string Common_AppName => Get("Common_AppName");

    /// <summary>Back</summary>
    public static string Common_Back => Get("Common_Back");

    /// <summary>Browse…</summary>
    public static string Common_Browse => Get("Common_Browse");

    /// <summary>Cancel</summary>
    public static string Common_Cancel => Get("Common_Cancel");

    /// <summary>Close</summary>
    public static string Common_Close => Get("Common_Close");

    /// <summary>Done</summary>
    public static string Common_Done => Get("Common_Done");

    /// <summary>Finish</summary>
    public static string Common_Finish => Get("Common_Finish");

    /// <summary>Loading…</summary>
    public static string Common_Loading => Get("Common_Loading");

    /// <summary>Next</summary>
    public static string Common_Next => Get("Common_Next");

    /// <summary>OK</summary>
    public static string Common_OK => Get("Common_OK");

    /// <summary>Off</summary>
    public static string Common_Off => Get("Common_Off");

    /// <summary>On</summary>
    public static string Common_On => Get("Common_On");

    /// <summary>Remove</summary>
    public static string Common_Remove => Get("Common_Remove");

    /// <summary>Try again</summary>
    public static string Common_Retry => Get("Common_Retry");

    /// <summary>Save</summary>
    public static string Common_Save => Get("Common_Save");

    /// <summary>Add images…</summary>
    public static string Defaults_AddImages => Get("Defaults_AddImages");

    /// <summary>Pause rotation while Battery Saver is on</summary>
    public static string Defaults_Battery => Get("Defaults_Battery");

    /// <summary>Games still switch your wallpaper.</summary>
    public static string Defaults_BatteryHelp => Get("Defaults_BatteryHelp");

    /// <summary>{0} wallpapers</summary>
    public static string Defaults_CollectionCount => Get("Defaults_CollectionCount");

    /// <summary>Downloads when first used</summary>
    public static string Defaults_CollectionNotDownloaded => Get("Defaults_CollectionNotDownloaded");

    /// <summary>Use {0}</summary>
    public static string Defaults_CollectionToggle => Get("Defaults_CollectionToggle");

    /// <summary>Collections</summary>
    public static string Defaults_Collections => Get("Defaults_Collections");

    /// <summary>PrettyDesk will list its wallpaper collections once its catalog has loaded. You can still use your own images below.</summary>
    public static string Defaults_CollectionsEmptyBody => Get("Defaults_CollectionsEmptyBody");

    /// <summary>No collections yet</summary>
    public static string Defaults_CollectionsEmptyTitle => Get("Defaults_CollectionsEmptyTitle");

    /// <summary>Choose from the wallpapers in your selection.</summary>
    public static string Defaults_FixedHelp => Get("Defaults_FixedHelp");

    /// <summary>Pick your wallpaper</summary>
    public static string Defaults_FixedPick => Get("Defaults_FixedPick");

    /// <summary>Match Windows light and dark mode</summary>
    public static string Defaults_FollowTheme => Get("Defaults_FollowTheme");

    /// <summary>Light wallpapers in light mode, dark in dark mode.</summary>
    public static string Defaults_FollowThemeHelp => Get("Defaults_FollowThemeHelp");

    /// <summary>{0} may look soft on your display: {1}</summary>
    public static string Defaults_ImageWarning => Get("Defaults_ImageWarning");

    /// <summary>{0} image(s) added.</summary>
    public static string Defaults_ImportDone => Get("Defaults_ImportDone");

    /// <summary>Couldn't add those images. Check that the files still exist and try again.</summary>
    public static string Defaults_ImportFailed => Get("Defaults_ImportFailed");

    /// <summary>{0} image(s) couldn't be added. {1}</summary>
    public static string Defaults_ImportSkipped => Get("Defaults_ImportSkipped");

    /// <summary>Change every</summary>
    public static string Defaults_Interval => Get("Defaults_Interval");

    /// <summary>Between 1 minute and 7 days (10080 minutes).</summary>
    public static string Defaults_IntervalCustomHelp => Get("Defaults_IntervalCustomHelp");

    /// <summary>Custom interval in minutes</summary>
    public static string Defaults_IntervalCustomMinutes => Get("Defaults_IntervalCustomMinutes");

    /// <summary>What your desktop shows when you're not playing a game.</summary>
    public static string Defaults_Intro => Get("Defaults_Intro");

    /// <summary>Keep at least one collection or image turned on.</summary>
    public static string Defaults_KeepOne => Get("Defaults_KeepOne");

    /// <summary>Wallpaper</summary>
    public static string Defaults_Mode => Get("Defaults_Mode");

    /// <summary>One fixed wallpaper</summary>
    public static string Defaults_ModeFixed => Get("Defaults_ModeFixed");

    /// <summary>Rotate through my selection</summary>
    public static string Defaults_ModeRotate => Get("Defaults_ModeRotate");

    /// <summary>My images</summary>
    public static string Defaults_MyImages => Get("Defaults_MyImages");

    /// <summary>You haven't added any images yet.</summary>
    public static string Defaults_MyImagesEmpty => Get("Defaults_MyImagesEmpty");

    /// <summary>Drag images here or choose them. They need at least 1280 px on the long edge. PrettyDesk keeps its own copy.</summary>
    public static string Defaults_MyImagesHelp => Get("Defaults_MyImagesHelp");

    /// <summary>Pick a collection first, then choose your wallpaper.</summary>
    public static string Defaults_NoFixedYet => Get("Defaults_NoFixedYet");

    /// <summary>Order</summary>
    public static string Defaults_Order => Get("Defaults_Order");

    /// <summary>Remove {0}</summary>
    public static string Defaults_RemoveImage => Get("Defaults_RemoveImage");

    /// <summary>Redo setup style</summary>
    public static string Defaults_SetupStyle => Get("Defaults_SetupStyle");

    /// <summary>Answer "What does your setup look like?" again.</summary>
    public static string Defaults_SetupStyleHelp => Get("Defaults_SetupStyleHelp");

    /// <summary>Wallpapers</summary>
    public static string Defaults_Title => Get("Defaults_Title");

    /// <summary>Include my images</summary>
    public static string Defaults_UseMyImages => Get("Defaults_UseMyImages");

    /// <summary>Something went wrong while starting. Details were saved to the log. You can try starting PrettyDesk again.</summary>
    public static string Error_StartupBody => Get("Error_StartupBody");

    /// <summary>PrettyDesk couldn't start properly</summary>
    public static string Error_StartupTitle => Get("Error_StartupTitle");

    /// <summary>Add my images…</summary>
    public static string Game_AddMyImages => Get("Game_AddMyImages");

    /// <summary>Add wallpapers…</summary>
    public static string Game_AddWallpapers => Get("Game_AddWallpapers");

    /// <summary>Back to Library</summary>
    public static string Game_Back => Get("Game_Back");

    /// <summary>Program: {0}</summary>
    public static string Game_DetectionExe => Get("Game_DetectionExe");

    /// <summary>You can see which program is running in Settings → Advanced → Detection log.</summary>
    public static string Game_DetectionHelp => Get("Game_DetectionHelp");

    /// <summary>No detection rules.</summary>
    public static string Game_DetectionNone => Get("Game_DetectionNone");

    /// <summary>Steam app: {0}</summary>
    public static string Game_DetectionSteam => Get("Game_DetectionSteam");

    /// <summary>How PrettyDesk recognises this game</summary>
    public static string Game_DetectionTitle => Get("Game_DetectionTitle");

    /// <summary>Download wallpapers</summary>
    public static string Game_Download => Get("Game_Download");

    /// <summary>The download didn't finish. Check your connection and try again.</summary>
    public static string Game_DownloadFailed => Get("Game_DownloadFailed");

    /// <summary>Downloading… {0}%</summary>
    public static string Game_Downloading => Get("Game_Downloading");

    /// <summary>Program names (one per line)</summary>
    public static string Game_EditExe => Get("Game_EditExe");

    /// <summary>The file name of the game, for example MyGame.exe.</summary>
    public static string Game_EditExeHelp => Get("Game_EditExeHelp");

    /// <summary>Change my wallpaper when I play this game</summary>
    public static string Game_Enabled => Get("Game_Enabled");

    /// <summary>Program names must end in .exe and can't contain folders.</summary>
    public static string Game_ExeInvalid => Get("Game_ExeInvalid");

    /// <summary>Use {0} as my favourite</summary>
    public static string Game_Favorite => Get("Game_Favorite");

    /// <summary>Include {0}</summary>
    public static string Game_Include => Get("Game_Include");

    /// <summary>Keep at least one wallpaper turned on.</summary>
    public static string Game_KeepOne => Get("Game_KeepOne");

    /// <summary>Wallpaper</summary>
    public static string Game_Mode => Get("Game_Mode");

    /// <summary>Always use my favourite</summary>
    public static string Game_ModeFixed => Get("Game_ModeFixed");

    /// <summary>Rotate through the wallpapers below</summary>
    public static string Game_ModeRotate => Get("Game_ModeRotate");

    /// <summary>This game has no wallpapers yet. Add some below.</summary>
    public static string Game_NoWallpapers => Get("Game_NoWallpapers");

    /// <summary>Not downloaded yet</summary>
    public static string Game_NotDownloaded => Get("Game_NotDownloaded");

    /// <summary>Order</summary>
    public static string Game_Order => Get("Game_Order");

    /// <summary>In order</summary>
    public static string Game_OrderSequential => Get("Game_OrderSequential");

    /// <summary>Shuffle</summary>
    public static string Game_OrderShuffle => Get("Game_OrderShuffle");

    /// <summary>This pack is not bundled and the content host is not configured. Use a ready default collection or add your own wallpaper.</summary>
    public static string Game_PackUnavailable => Get("Game_PackUnavailable");

    /// <summary>Prepare wallpapers before I play</summary>
    public static string Game_Prefetch => Get("Game_Prefetch");

    /// <summary>Download only the formats your displays need. Requires installed-game downloads to be enabled in Settings.</summary>
    public static string Game_PrefetchHelp => Get("Game_PrefetchHelp");

    /// <summary>Preview on desktop</summary>
    public static string Game_Preview => Get("Game_Preview");

    /// <summary>Shows it for 15 seconds, then goes back.</summary>
    public static string Game_PreviewHelp => Get("Game_PreviewHelp");

    /// <summary>Remove this game</summary>
    public static string Game_RemoveGame => Get("Game_RemoveGame");

    /// <summary>PrettyDesk will stop changing your wallpaper for it. Your images stay on your PC.</summary>
    public static string Game_RemoveMessage => Get("Game_RemoveMessage");

    /// <summary>Remove {0}?</summary>
    public static string Game_RemoveTitle => Get("Game_RemoveTitle");

    /// <summary>Change wallpaper</summary>
    public static string Game_Rotation => Get("Game_Rotation");

    /// <summary>By default a game keeps one wallpaper for the whole session and shows the next one next time.</summary>
    public static string Game_RotationHelp => Get("Game_RotationHelp");

    /// <summary>Suggest this game to PrettyDesk</summary>
    public static string Game_Suggest => Get("Game_Suggest");

    /// <summary>Opens a prefilled GitHub issue with only the program name and display name. Nothing is sent until you press Submit there.</summary>
    public static string Game_SuggestHelp => Get("Game_SuggestHelp");

    /// <summary>Stop using {0} as my favourite</summary>
    public static string Game_Unfavorite => Get("Game_Unfavorite");

    /// <summary>Wallpapers</summary>
    public static string Game_WallpapersTitle => Get("Game_WallpapersTitle");

    /// <summary>Display {0} · {1}×{2}</summary>
    public static string Home_DisplayLabel => Get("Home_DisplayLabel");

    /// <summary>Explore wallpapers</summary>
    public static string Home_GlassAction => Get("Home_GlassAction");

    /// <summary>Explore Liquid Glass: three original iOS-inspired wallpapers, ready offline.</summary>
    public static string Home_GlassDetail => Get("Home_GlassDetail");

    /// <summary>A little clarity. A whole new desktop.</summary>
    public static string Home_GlassTitle => Get("Home_GlassTitle");

    /// <summary>Next wallpaper</summary>
    public static string Home_NextWallpaper => Get("Home_NextWallpaper");

    /// <summary>No display detected</summary>
    public static string Home_NoMonitors => Get("Home_NoMonitors");

    /// <summary>PrettyDesk will pick up your screens as soon as Windows reports them.</summary>
    public static string Home_NoMonitorsDetail => Get("Home_NoMonitorsDetail");

    /// <summary>No wallpaper yet</summary>
    public static string Home_NoWallpaperYet => Get("Home_NoWallpaperYet");

    /// <summary>Pause</summary>
    public static string Home_Pause => Get("Home_Pause");

    /// <summary>Pause for 1 hour</summary>
    public static string Home_PauseOneHour => Get("Home_PauseOneHour");

    /// <summary>Pause until I resume</summary>
    public static string Home_PauseUntilResumed => Get("Home_PauseUntilResumed");

    /// <summary>Your desktop right now</summary>
    public static string Home_PreviewLabel => Get("Home_PreviewLabel");

    /// <summary>Display {0} · {1}×{2} (main)</summary>
    public static string Home_PrimaryDisplay => Get("Home_PrimaryDisplay");

    /// <summary>Resume</summary>
    public static string Home_Resume => Get("Home_Resume");

    /// <summary>Home</summary>
    public static string Home_Title => Get("Home_Title");

    /// <summary>Custom…</summary>
    public static string Interval_Custom => Get("Interval_Custom");

    /// <summary>Daily</summary>
    public static string Interval_Daily => Get("Interval_Daily");

    /// <summary>Every {0} days</summary>
    public static string Interval_Days => Get("Interval_Days");

    /// <summary>Every hour</summary>
    public static string Interval_Hour => Get("Interval_Hour");

    /// <summary>Every {0} hours</summary>
    public static string Interval_Hours => Get("Interval_Hours");

    /// <summary>Every {0} minutes</summary>
    public static string Interval_Minutes => Get("Interval_Minutes");

    /// <summary>Never</summary>
    public static string Interval_Never => Get("Interval_Never");

    /// <summary>Next session</summary>
    public static string Interval_Session => Get("Interval_Session");

    /// <summary>On every unlock</summary>
    public static string Interval_Unlock => Get("Interval_Unlock");

    /// <summary>Add a game</summary>
    public static string Library_AddGame => Get("Library_AddGame");

    /// <summary>Added by you</summary>
    public static string Library_ChipCustom => Get("Library_ChipCustom");

    /// <summary>Downloading {0}%</summary>
    public static string Library_ChipDownloading => Get("Library_ChipDownloading");

    /// <summary>Download failed</summary>
    public static string Library_ChipFailed => Get("Library_ChipFailed");

    /// <summary>Installed</summary>
    public static string Library_ChipInstalled => Get("Library_ChipInstalled");

    /// <summary>Not downloaded</summary>
    public static string Library_ChipNotDownloaded => Get("Library_ChipNotDownloaded");

    /// <summary>Ready</summary>
    public static string Library_ChipReady => Get("Library_ChipReady");

    /// <summary>Unavailable offline</summary>
    public static string Library_ChipUnavailable => Get("Library_ChipUnavailable");

    /// <summary>Wallpapers are original art inspired by each game. PrettyDesk is not affiliated with any game publisher.</summary>
    public static string Library_DisclaimerNote => Get("Library_DisclaimerNote");

    /// <summary>PrettyDesk will fill this in as soon as it can reach its game catalog. You can still add any game yourself.</summary>
    public static string Library_EmptyCatalogBody => Get("Library_EmptyCatalogBody");

    /// <summary>The game list isn't available yet</summary>
    public static string Library_EmptyCatalogTitle => Get("Library_EmptyCatalogTitle");

    /// <summary>Turn a game on to give it its own wallpaper.</summary>
    public static string Library_EmptyEnabledBody => Get("Library_EmptyEnabledBody");

    /// <summary>No games are turned on</summary>
    public static string Library_EmptyEnabledTitle => Get("Library_EmptyEnabledTitle");

    /// <summary>PrettyDesk looks at your Steam and Epic libraries. Games from other launchers can be added with Add a game.</summary>
    public static string Library_EmptyInstalledBody => Get("Library_EmptyInstalledBody");

    /// <summary>No installed games found</summary>
    public static string Library_EmptyInstalledTitle => Get("Library_EmptyInstalledTitle");

    /// <summary>Try a different name, or switch the filter back to All.</summary>
    public static string Library_EmptySearchBody => Get("Library_EmptySearchBody");

    /// <summary>No games match</summary>
    public static string Library_EmptySearchTitle => Get("Library_EmptySearchTitle");

    /// <summary>All</summary>
    public static string Library_FilterAll => Get("Library_FilterAll");

    /// <summary>Enabled</summary>
    public static string Library_FilterEnabled => Get("Library_FilterEnabled");

    /// <summary>Installed</summary>
    public static string Library_FilterInstalled => Get("Library_FilterInstalled");

    /// <summary>Show wallpapers for {0}</summary>
    public static string Library_GameToggle => Get("Library_GameToggle");

    /// <summary>Search games</summary>
    public static string Library_Search => Get("Library_Search");

    /// <summary>Library</summary>
    public static string Library_Title => Get("Library_Title");

    /// <summary>About</summary>
    public static string Nav_About => Get("Nav_About");

    /// <summary>Wallpapers</summary>
    public static string Nav_Defaults => Get("Nav_Defaults");

    /// <summary>Home</summary>
    public static string Nav_Home => Get("Nav_Home");

    /// <summary>Library</summary>
    public static string Nav_Library => Get("Nav_Library");

    /// <summary>Settings</summary>
    public static string Nav_Settings => Get("Nav_Settings");

    /// <summary>The wallpapers for {0} didn't download. PrettyDesk will keep your current wallpaper and try again later.</summary>
    public static string Notify_DownloadFailedBody => Get("Notify_DownloadFailedBody");

    /// <summary>Couldn't download wallpapers</summary>
    public static string Notify_DownloadFailedTitle => Get("Notify_DownloadFailedTitle");

    /// <summary>PrettyDesk couldn't read its settings file, so it started fresh. The old file was kept next to it.</summary>
    public static string Notify_SettingsRecoveredBody => Get("Notify_SettingsRecoveredBody");

    /// <summary>Your settings were reset</summary>
    public static string Notify_SettingsRecoveredTitle => Get("Notify_SettingsRecoveredTitle");

    /// <summary>Add game</summary>
    public static string Notify_UnknownGameAction => Get("Notify_UnknownGameAction");

    /// <summary>Add {0} to PrettyDesk to give it its own wallpapers.</summary>
    public static string Notify_UnknownGameBody => Get("Notify_UnknownGameBody");

    /// <summary>Is that a game?</summary>
    public static string Notify_UnknownGameTitle => Get("Notify_UnknownGameTitle");

    /// <summary>Version {0} is ready. Open About to restart and update.</summary>
    public static string Notify_UpdateBody => Get("Notify_UpdateBody");

    /// <summary>PrettyDesk update available</summary>
    public static string Notify_UpdateTitle => Get("Notify_UpdateTitle");

    /// <summary>Ready for your displays · no download needed</summary>
    public static string Onboard_AlreadyIncluded => Get("Onboard_AlreadyIncluded");

    /// <summary>Continue while downloads run. Unchecking stops future downloads; active downloads continue.</summary>
    public static string Onboard_BackgroundHelp => Get("Onboard_BackgroundHelp");

    /// <summary>Only the formats your displays need. Same-shaped displays share one download; resolution is adjusted automatically.</summary>
    public static string Onboard_DisplayFitHelp => Get("Onboard_DisplayFitHelp");

    /// <summary>{0} × {1}×{2} · {3}</summary>
    public static string Onboard_DisplayGroup => Get("Onboard_DisplayGroup");

    /// <summary>No displays detected. You can continue and download later in Library.</summary>
    public static string Onboard_DisplaysMissing => Get("Onboard_DisplaysMissing");

    /// <summary>PrettyDesk is now in your system tray. Close this window any time. It keeps working quietly in the background.</summary>
    public static string Onboard_DoneBody => Get("Onboard_DoneBody");

    /// <summary>Tip: right-click the tray icon to change wallpaper or pause.</summary>
    public static string Onboard_DoneTip => Get("Onboard_DoneTip");

    /// <summary>You're all set</summary>
    public static string Onboard_DoneTitle => Get("Onboard_DoneTitle");

    /// <summary>Prepare selected game wallpapers automatically</summary>
    public static string Onboard_DownloadBackground => Get("Onboard_DownloadBackground");

    /// <summary>Downloading · {0}%</summary>
    public static string Onboard_DownloadProgress => Get("Onboard_DownloadProgress");

    /// <summary>Download failed. Select Download selected to retry, or continue and try later.</summary>
    public static string Onboard_DownloadRetry => Get("Onboard_DownloadRetry");

    /// <summary>Download selected</summary>
    public static string Onboard_DownloadSelected => Get("Onboard_DownloadSelected");

    /// <summary>Selected: {0} · up to {1} to download</summary>
    public static string Onboard_DownloadTotal => Get("Onboard_DownloadTotal");

    /// <summary>Downloads are unavailable right now. Included wallpapers still work offline.</summary>
    public static string Onboard_DownloadUnavailable => Get("Onboard_DownloadUnavailable");

    /// <summary>Couldn't save your choices. Check that there's free disk space and try again.</summary>
    public static string Onboard_Failed => Get("Onboard_Failed");

    /// <summary>Some wallpapers use the closest available format and are cropped to fit.</summary>
    public static string Onboard_FormatFallback => Get("Onboard_FormatFallback");

    /// <summary>Landscape 16:9</summary>
    public static string Onboard_FormatLandscape => Get("Onboard_FormatLandscape");

    /// <summary>Portrait 9:16</summary>
    public static string Onboard_FormatPortrait => Get("Onboard_FormatPortrait");

    /// <summary>Super ultrawide 32:9</summary>
    public static string Onboard_FormatSuperwide => Get("Onboard_FormatSuperwide");

    /// <summary>Ultrawide 21:9</summary>
    public static string Onboard_FormatUltrawide => Get("Onboard_FormatUltrawide");

    /// <summary>Turn on the games you want PrettyDesk to recognise. Everything stays on your PC.</summary>
    public static string Onboard_GamesBody => Get("Onboard_GamesBody");

    /// <summary>That's fine. PrettyDesk also recognises games as you launch them, and you can add any game later in Library.</summary>
    public static string Onboard_GamesEmptyBody => Get("Onboard_GamesEmptyBody");

    /// <summary>No supported games found yet</summary>
    public static string Onboard_GamesEmptyTitle => Get("Onboard_GamesEmptyTitle");

    /// <summary>Looking at your Steam and Epic libraries…</summary>
    public static string Onboard_GamesLoading => Get("Onboard_GamesLoading");

    /// <summary>Games we found on this PC</summary>
    public static string Onboard_GamesTitle => Get("Onboard_GamesTitle");

    /// <summary>{0} MB</summary>
    public static string Onboard_Megabytes => Get("Onboard_Megabytes");

    /// <summary>This is what you see when you're not in a game.</summary>
    public static string Onboard_ModeBody => Get("Onboard_ModeBody");

    /// <summary>One wallpaper</summary>
    public static string Onboard_ModeFixed => Get("Onboard_ModeFixed");

    /// <summary>Change every</summary>
    public static string Onboard_ModeInterval => Get("Onboard_ModeInterval");

    /// <summary>Rotate wallpapers</summary>
    public static string Onboard_ModeRotate => Get("Onboard_ModeRotate");

    /// <summary>How should your desktop behave?</summary>
    public static string Onboard_ModeTitle => Get("Onboard_ModeTitle");

    /// <summary>Nothing selected needs downloading.</summary>
    public static string Onboard_NoDownloadsNeeded => Get("Onboard_NoDownloadsNeeded");

    /// <summary>Your included default wallpapers are ready. You can add games and download more from Library later.</summary>
    public static string Onboard_NoGamePacks => Get("Onboard_NoGamePacks");

    /// <summary>No matching artwork is available yet. You can add your own images later.</summary>
    public static string Onboard_NoMatchingArt => Get("Onboard_NoMatchingArt");

    /// <summary>{0} to download · {1}</summary>
    public static string Onboard_PackDownloadSize => Get("Onboard_PackDownloadSize");

    /// <summary>We could not check your installed games. Try again, or continue and add games in Library later.</summary>
    public static string Onboard_ScanFailed => Get("Onboard_ScanFailed");

    /// <summary>Check again</summary>
    public static string Onboard_ScanRetry => Get("Onboard_ScanRetry");

    /// <summary>PrettyDesk restores your slideshow source, shuffle setting, and interval. Windows Spotlight remains unchanged until you switch Windows Background to Picture or Slideshow.</summary>
    public static string Onboard_SpotlightNote => Get("Onboard_SpotlightNote");

    /// <summary>Get started</summary>
    public static string Onboard_Start => Get("Onboard_Start");

    /// <summary>So your wallpapers switch the moment you start a game. PrettyDesk starts quietly in the tray.</summary>
    public static string Onboard_StartupBody => Get("Onboard_StartupBody");

    /// <summary>Start with Windows</summary>
    public static string Onboard_StartupTitle => Get("Onboard_StartupTitle");

    /// <summary>Start PrettyDesk when I sign in</summary>
    public static string Onboard_StartupToggle => Get("Onboard_StartupToggle");

    /// <summary>Step {0} of {1}</summary>
    public static string Onboard_StepOf => Get("Onboard_StepOf");

    /// <summary>We'll pick wallpapers that match your desk. You can change this any time.</summary>
    public static string Onboard_StyleBody => Get("Onboard_StyleBody");

    /// <summary>Clean white</summary>
    public static string Onboard_StyleCleanWhite => Get("Onboard_StyleCleanWhite");

    /// <summary>Bright, airy, calm</summary>
    public static string Onboard_StyleCleanWhiteHelp => Get("Onboard_StyleCleanWhiteHelp");

    /// <summary>Matte black</summary>
    public static string Onboard_StyleMatteBlack => Get("Onboard_StyleMatteBlack");

    /// <summary>Dark, minimal, OLED-friendly</summary>
    public static string Onboard_StyleMatteBlackHelp => Get("Onboard_StyleMatteBlackHelp");

    /// <summary>Pastel</summary>
    public static string Onboard_StylePastel => Get("Onboard_StylePastel");

    /// <summary>Soft colours and dreamy skies</summary>
    public static string Onboard_StylePastelHelp => Get("Onboard_StylePastelHelp");

    /// <summary>RGB</summary>
    public static string Onboard_StyleRgb => Get("Onboard_StyleRgb");

    /// <summary>Dark with a single neon glow</summary>
    public static string Onboard_StyleRgbHelp => Get("Onboard_StyleRgbHelp");

    /// <summary>Surprise me</summary>
    public static string Onboard_StyleSurprise => Get("Onboard_StyleSurprise");

    /// <summary>One favourite from every collection</summary>
    public static string Onboard_StyleSurpriseHelp => Get("Onboard_StyleSurpriseHelp");

    /// <summary>What does your setup look like?</summary>
    public static string Onboard_StyleTitle => Get("Onboard_StyleTitle");

    /// <summary>Warm wood and plants</summary>
    public static string Onboard_StyleWarmWood => Get("Onboard_StyleWarmWood");

    /// <summary>Natural, cosy, sunlit</summary>
    public static string Onboard_StyleWarmWoodHelp => Get("Onboard_StyleWarmWoodHelp");

    /// <summary>Choose the games to prepare now. We select the wallpaper formats your displays need.</summary>
    public static string Onboard_WallpapersBody => Get("Onboard_WallpapersBody");

    /// <summary>Wallpapers for your setup</summary>
    public static string Onboard_WallpapersTitle => Get("Onboard_WallpapersTitle");

    /// <summary>Your desktop looks great even while you play. PrettyDesk switches to wallpapers inspired by your game, then goes back to your clean setup when you stop.</summary>
    public static string Onboard_WelcomeBody => Get("Onboard_WelcomeBody");

    /// <summary>Runs quietly in the tray. No account, no admin rights.</summary>
    public static string Onboard_WelcomePoint1 => Get("Onboard_WelcomePoint1");

    /// <summary>Never touches your games or anti-cheat.</summary>
    public static string Onboard_WelcomePoint2 => Get("Onboard_WelcomePoint2");

    /// <summary>One click restores your original wallpaper.</summary>
    public static string Onboard_WelcomePoint3 => Get("Onboard_WelcomePoint3");

    /// <summary>Welcome to PrettyDesk</summary>
    public static string Onboard_WelcomeTitle => Get("Onboard_WelcomeTitle");

    /// <summary>Use selected</summary>
    public static string Picker_Confirm => Get("Picker_Confirm");

    /// <summary>Nothing to choose from yet. Download a collection or add your own images.</summary>
    public static string Picker_Empty => Get("Picker_Empty");

    /// <summary>My images</summary>
    public static string Picker_GroupMine => Get("Picker_GroupMine");

    /// <summary>Search wallpapers</summary>
    public static string Picker_Search => Get("Picker_Search");

    /// <summary>{0} selected</summary>
    public static string Picker_Selected => Get("Picker_Selected");

    /// <summary>Choose wallpapers</summary>
    public static string Picker_Title => Get("Picker_Title");

    /// <summary>Advanced</summary>
    public static string Settings_Advanced => Get("Settings_Advanced");

    /// <summary>App theme</summary>
    public static string Settings_AppTheme => Get("Settings_AppTheme");

    /// <summary>Follow Windows, or choose Light or Dark. High contrast always takes precedence.</summary>
    public static string Settings_AppThemeHelp => Get("Settings_AppThemeHelp");

    /// <summary>Get beta versions</summary>
    public static string Settings_BetaUpdates => Get("Settings_BetaUpdates");

    /// <summary>Try new features early. Beta versions can be less stable, and you can switch back at any time.</summary>
    public static string Settings_BetaUpdatesHelp => Get("Settings_BetaUpdatesHelp");

    /// <summary>Clear downloaded content</summary>
    public static string Settings_ClearDownloads => Get("Settings_ClearDownloads");

    /// <summary>Freed {0}.</summary>
    public static string Settings_ClearDownloadsDone => Get("Settings_ClearDownloadsDone");

    /// <summary>Couldn't clear everything. Some files may be in use. Try again in a moment.</summary>
    public static string Settings_ClearDownloadsFailed => Get("Settings_ClearDownloadsFailed");

    /// <summary>Wallpapers will download again when you next need them. Your own images aren't touched.</summary>
    public static string Settings_ClearDownloadsMessage => Get("Settings_ClearDownloadsMessage");

    /// <summary>Clear downloaded wallpapers?</summary>
    public static string Settings_ClearDownloadsTitle => Get("Settings_ClearDownloadsTitle");

    /// <summary>Clock display</summary>
    public static string Settings_ClockMonitor => Get("Settings_ClockMonitor");

    /// <summary>Desktop clock</summary>
    public static string Settings_DesktopClock => Get("Settings_DesktopClock");

    /// <summary>Show a quiet clock on the desktop. It hides while a game is active, the session is locked or battery saver is on.</summary>
    public static string Settings_DesktopClockHelp => Get("Settings_DesktopClockHelp");

    /// <summary>Switch wallpaper after a game has run for</summary>
    public static string Settings_DetectDelay => Get("Settings_DetectDelay");

    /// <summary>Avoids switching when a game crashes right away or a launcher hands off.</summary>
    public static string Settings_DetectDelayHelp => Get("Settings_DetectDelayHelp");

    /// <summary>Detect games</summary>
    public static string Settings_DetectGames => Get("Settings_DetectGames");

    /// <summary>Turn this off to keep your wallpaper fixed no matter what you play.</summary>
    public static string Settings_DetectGamesHelp => Get("Settings_DetectGamesHelp");

    /// <summary>Detection</summary>
    public static string Settings_Detection => Get("Settings_Detection");

    /// <summary>Detection log</summary>
    public static string Settings_DetectionLog => Get("Settings_DetectionLog");

    /// <summary>Clear</summary>
    public static string Settings_DetectionLogClear => Get("Settings_DetectionLogClear");

    /// <summary>Waiting for you to switch to a game…</summary>
    public static string Settings_DetectionLogEmpty => Get("Settings_DetectionLogEmpty");

    /// <summary>Shows the app you're using and any game PrettyDesk recognises. Use it to check a game's exe name. It's shown here only and never saved.</summary>
    public static string Settings_DetectionLogHelp => Get("Settings_DetectionLogHelp");

    /// <summary>{0}  {1}  {2}</summary>
    public static string Settings_DetectionLogLine => Get("Settings_DetectionLogLine");

    /// <summary>matches: {0}</summary>
    public static string Settings_DetectionLogMatched => Get("Settings_DetectionLogMatched");

    /// <summary>(no foreground app)</summary>
    public static string Settings_DetectionLogNoForeground => Get("Settings_DetectionLogNoForeground");

    /// <summary>no catalog match</summary>
    public static string Settings_DetectionLogNoMatch => Get("Settings_DetectionLogNoMatch");

    /// <summary>Pause log</summary>
    public static string Settings_DetectionLogPause => Get("Settings_DetectionLogPause");

    /// <summary>Resume log</summary>
    public static string Settings_DetectionLogResume => Get("Settings_DetectionLogResume");

    /// <summary>Keep the game wallpaper after it closes for</summary>
    public static string Settings_ExitGrace => Get("Settings_ExitGrace");

    /// <summary>Covers games that restart themselves after a patch or a settings change.</summary>
    public static string Settings_ExitGraceHelp => Get("Settings_ExitGraceHelp");

    /// <summary>Export diagnostics</summary>
    public static string Settings_ExportDiagnostics => Get("Settings_ExportDiagnostics");

    /// <summary>Creates a zip with logs, settings and display info. It never includes a list of your running apps.</summary>
    public static string Settings_ExportDiagnosticsHelp => Get("Settings_ExportDiagnosticsHelp");

    /// <summary>Saved to {0}</summary>
    public static string Settings_ExportDone => Get("Settings_ExportDone");

    /// <summary>Couldn't create the diagnostics file. Check that there's free disk space and try again.</summary>
    public static string Settings_ExportFailed => Get("Settings_ExportFailed");

    /// <summary>Only change my other displays during games</summary>
    public static string Settings_GameOnSecondaryOnly => Get("Settings_GameOnSecondaryOnly");

    /// <summary>Your main display keeps your default wallpaper.</summary>
    public static string Settings_GameOnSecondaryOnlyHelp => Get("Settings_GameOnSecondaryOnlyHelp");

    /// <summary>General</summary>
    public static string Settings_General => Get("Settings_General");

    /// <summary>No active media session supports this control.</summary>
    public static string Settings_MediaUnavailable => Get("Settings_MediaUnavailable");

    /// <summary>A different wallpaper on each display</summary>
    public static string Settings_MonitorDifferent => Get("Settings_MonitorDifferent");

    /// <summary>Wallpaper on multiple displays</summary>
    public static string Settings_MonitorMode => Get("Settings_MonitorMode");

    /// <summary>Same wallpaper on every display</summary>
    public static string Settings_MonitorSame => Get("Settings_MonitorSame");

    /// <summary>Monitors</summary>
    public static string Settings_Monitors => Get("Settings_Monitors");

    /// <summary>Next track</summary>
    public static string Settings_NextTrack => Get("Settings_NextTrack");

    /// <summary>Notifications</summary>
    public static string Settings_Notifications => Get("Settings_Notifications");

    /// <summary>Tell me when a download fails</summary>
    public static string Settings_NotifyDownloadErrors => Get("Settings_NotifyDownloadErrors");

    /// <summary>PrettyDesk never notifies you when the wallpaper changes.</summary>
    public static string Settings_NotifyHelp => Get("Settings_NotifyHelp");

    /// <summary>Tell me when I might want to add a game</summary>
    public static string Settings_NotifyUnknownGames => Get("Settings_NotifyUnknownGames");

    /// <summary>Tell me when an update is available</summary>
    public static string Settings_NotifyUpdates => Get("Settings_NotifyUpdates");

    /// <summary>Show now playing</summary>
    public static string Settings_NowPlaying => Get("Settings_NowPlaying");

    /// <summary>Open Windows Colors</summary>
    public static string Settings_OpenColors => Get("Settings_OpenColors");

    /// <summary>Open logs folder</summary>
    public static string Settings_OpenLogs => Get("Settings_OpenLogs");

    /// <summary>Play / pause</summary>
    public static string Settings_PlayPause => Get("Settings_PlayPause");

    /// <summary>Check for games every</summary>
    public static string Settings_PollSeconds => Get("Settings_PollSeconds");

    /// <summary>{0} s</summary>
    public static string Settings_PollSecondsValue => Get("Settings_PollSecondsValue");

    /// <summary>Download wallpapers for games I have installed</summary>
    public static string Settings_PrefetchGames => Get("Settings_PrefetchGames");

    /// <summary>So the right wallpaper is ready the moment a game starts.</summary>
    public static string Settings_PrefetchGamesHelp => Get("Settings_PrefetchGamesHelp");

    /// <summary>Reset PrettyDesk</summary>
    public static string Settings_ResetApp => Get("Settings_ResetApp");

    /// <summary>Puts all settings back to their defaults and removes downloaded wallpapers.</summary>
    public static string Settings_ResetAppHelp => Get("Settings_ResetAppHelp");

    /// <summary>Couldn't reset PrettyDesk. Close any program that is using the PrettyDesk folder and try again.</summary>
    public static string Settings_ResetFailed => Get("Settings_ResetFailed");

    /// <summary>Reset, keep my images</summary>
    public static string Settings_ResetKeepImages => Get("Settings_ResetKeepImages");

    /// <summary>This resets every setting and removes downloaded wallpapers. Do you also want to remove the images you added yourself?</summary>
    public static string Settings_ResetMessage => Get("Settings_ResetMessage");

    /// <summary>Reset and remove my images</summary>
    public static string Settings_ResetRemoveImages => Get("Settings_ResetRemoveImages");

    /// <summary>Reset PrettyDesk?</summary>
    public static string Settings_ResetTitle => Get("Settings_ResetTitle");

    /// <summary>Restore original wallpaper</summary>
    public static string Settings_Restore => Get("Settings_Restore");

    /// <summary>Your original wallpaper is back.</summary>
    public static string Settings_RestoreDone => Get("Settings_RestoreDone");

    /// <summary>Couldn't restore your wallpaper. Try again in a moment.</summary>
    public static string Settings_RestoreFailed => Get("Settings_RestoreFailed");

    /// <summary>PrettyDesk will stop at your original wallpaper until you change something.</summary>
    public static string Settings_RestoreMessage => Get("Settings_RestoreMessage");

    /// <summary>There's no saved original wallpaper yet. PrettyDesk saves it the first time it changes your wallpaper.</summary>
    public static string Settings_RestoreNothing => Get("Settings_RestoreNothing");

    /// <summary>Restore my original wallpaper when PrettyDesk exits</summary>
    public static string Settings_RestoreOnExit => Get("Settings_RestoreOnExit");

    /// <summary>Closing the window never does this. Only quitting from the tray menu.</summary>
    public static string Settings_RestoreOnExitHelp => Get("Settings_RestoreOnExitHelp");

    /// <summary>Restore my original wallpaper</summary>
    public static string Settings_RestoreOriginal => Get("Settings_RestoreOriginal");

    /// <summary>Puts back the wallpaper you had before PrettyDesk first changed it. This works even if the original file was deleted.</summary>
    public static string Settings_RestoreOriginalHelp => Get("Settings_RestoreOriginalHelp");

    /// <summary>Restore your original wallpaper?</summary>
    public static string Settings_RestoreTitle => Get("Settings_RestoreTitle");

    /// <summary>Restoring…</summary>
    public static string Settings_Restoring => Get("Settings_Restoring");

    /// <summary>Show in folder</summary>
    public static string Settings_ShowInFolder => Get("Settings_ShowInFolder");

    /// <summary>Start with Windows</summary>
    public static string Settings_StartWithWindows => Get("Settings_StartWithWindows");

    /// <summary>PrettyDesk runs quietly in the tray. It never needs administrator rights.</summary>
    public static string Settings_StartWithWindowsHelp => Get("Settings_StartWithWindowsHelp");

    /// <summary>Storage</summary>
    public static string Settings_Storage => Get("Settings_Storage");

    /// <summary>Keep downloads under</summary>
    public static string Settings_StorageCap => Get("Settings_StorageCap");

    /// <summary>{0} GB</summary>
    public static string Settings_StorageCapValue => Get("Settings_StorageCapValue");

    /// <summary>Downloaded wallpapers use {0}</summary>
    public static string Settings_StorageUsed => Get("Settings_StorageUsed");

    /// <summary>Settings</summary>
    public static string Settings_Title => Get("Settings_Title");

    /// <summary>Offer to add games PrettyDesk doesn't know</summary>
    public static string Settings_UnknownGameHints => Get("Settings_UnknownGameHints");

    /// <summary>After a full-screen app has run for a minute, PrettyDesk can ask once whether to add it. Nothing is sent anywhere.</summary>
    public static string Settings_UnknownGameHintsHelp => Get("Settings_UnknownGameHintsHelp");

    /// <summary>Playback visualizer</summary>
    public static string Settings_Visualizer => Get("Settings_Visualizer");

    /// <summary>Analyze the default output device locally, at up to 15 frames per second. No microphone, recordings or uploads. Stops during games, lock and battery saver; respects reduced motion.</summary>
    public static string Settings_VisualizerHelp => Get("Settings_VisualizerHelp");

    /// <summary>Windows taskbar and colors</summary>
    public static string Settings_WindowsColors => Get("Settings_WindowsColors");

    /// <summary>Windows controls taskbar transparency and automatic wallpaper accent. Open Colors to choose your preferences.</summary>
    public static string Settings_WindowsColorsHelp => Get("Settings_WindowsColorsHelp");

    /// <summary>Working…</summary>
    public static string Settings_Working => Get("Settings_Working");

    /// <summary>Main navigation</summary>
    public static string Shell_NavLabel => Get("Shell_NavLabel");

    /// <summary>Couldn't change the wallpaper. Trying again…</summary>
    public static string Status_ApplyFailed => Get("Status_ApplyFailed");

    /// <summary>Your organization manages your wallpaper</summary>
    public static string Status_Blocked => Get("Status_Blocked");

    /// <summary>PrettyDesk can't change it on this PC.</summary>
    public static string Status_BlockedDetail => Get("Status_BlockedDetail");

    /// <summary>Default · {0}</summary>
    public static string Status_DefaultFixed => Get("Status_DefaultFixed");

    /// <summary>Next change {0}</summary>
    public static string Status_DefaultNextChange => Get("Status_DefaultNextChange");

    /// <summary>No wallpapers are available yet</summary>
    public static string Status_DefaultNoContent => Get("Status_DefaultNoContent");

    /// <summary>Pick a collection in Defaults, or add your own images.</summary>
    public static string Status_DefaultNoContentDetail => Get("Status_DefaultNoContentDetail");

    /// <summary>Default · {0} (rotating)</summary>
    public static string Status_DefaultRotating => Get("Status_DefaultRotating");

    /// <summary>Returning to your default wallpaper soon</summary>
    public static string Status_GameEnded => Get("Status_GameEnded");

    /// <summary>Getting {0} wallpapers…</summary>
    public static string Status_GameLoading => Get("Status_GameLoading");

    /// <summary>Your current wallpaper stays until they're ready.</summary>
    public static string Status_GameLoadingDetail => Get("Status_GameLoadingDetail");

    /// <summary>Paused</summary>
    public static string Status_Paused => Get("Status_Paused");

    /// <summary>Paused until you resume</summary>
    public static string Status_PausedIndefinite => Get("Status_PausedIndefinite");

    /// <summary>Paused until {0}</summary>
    public static string Status_PausedUntil => Get("Status_PausedUntil");

    /// <summary>Playing: {0}</summary>
    public static string Status_Playing => Get("Status_Playing");

    /// <summary>Wallpaper {0} of {1}</summary>
    public static string Status_PlayingDetailPosition => Get("Status_PlayingDetailPosition");

    /// <summary>Previewing a wallpaper</summary>
    public static string Status_Preview => Get("Status_Preview");

    /// <summary>It goes back to normal in a few seconds.</summary>
    public static string Status_PreviewDetail => Get("Status_PreviewDetail");

    /// <summary>Starting…</summary>
    public static string Status_Starting => Get("Status_Starting");

    /// <summary>in {0} days</summary>
    public static string Time_Days => Get("Time_Days");

    /// <summary>in {0} h</summary>
    public static string Time_Hours => Get("Time_Hours");

    /// <summary>in {0} h {1} min</summary>
    public static string Time_HoursMinutes => Get("Time_HoursMinutes");

    /// <summary>in {0} min</summary>
    public static string Time_Minutes => Get("Time_Minutes");

    /// <summary>in 1 day</summary>
    public static string Time_OneDay => Get("Time_OneDay");

    /// <summary>in under a minute</summary>
    public static string Time_UnderMinute => Get("Time_UnderMinute");

    /// <summary>It lives in your system tray. Right-click the icon to change wallpaper, pause or quit.</summary>
    public static string Tray_FirstHideBody => Get("Tray_FirstHideBody");

    /// <summary>PrettyDesk is still running</summary>
    public static string Tray_FirstHideTitle => Get("Tray_FirstHideTitle");

    /// <summary>Next wallpaper</summary>
    public static string Tray_Next => Get("Tray_Next");

    /// <summary>Open PrettyDesk</summary>
    public static string Tray_Open => Get("Tray_Open");

    /// <summary>Pause</summary>
    public static string Tray_Pause => Get("Tray_Pause");

    /// <summary>For 1 hour</summary>
    public static string Tray_PauseOneHour => Get("Tray_PauseOneHour");

    /// <summary>Until I resume</summary>
    public static string Tray_PauseUntilResumed => Get("Tray_PauseUntilResumed");

    /// <summary>Quit</summary>
    public static string Tray_Quit => Get("Tray_Quit");

    /// <summary>Resume</summary>
    public static string Tray_Resume => Get("Tray_Resume");

    /// <summary>PrettyDesk</summary>
    public static string Tray_Tooltip => Get("Tray_Tooltip");

    /// <summary>Do you also want to delete your PrettyDesk settings, downloaded wallpapers and your own images?  Choose No to keep them in case you reinstall.</summary>
    public static string Uninstall_KeepDataBody => Get("Uninstall_KeepDataBody");

    /// <summary>Uninstalling PrettyDesk</summary>
    public static string Uninstall_KeepDataTitle => Get("Uninstall_KeepDataTitle");

    /// <summary>Default playback output</summary>
    public static string Widget_DefaultOutput => Get("Widget_DefaultOutput");

    /// <summary>Now playing unavailable</summary>
    public static string Widget_MediaUnavailable => Get("Widget_MediaUnavailable");

    /// <summary>Nothing playing</summary>
    public static string Widget_NothingPlaying => Get("Widget_NothingPlaying");

    /// <summary>Playback device unavailable. Retrying…</summary>
    public static string Widget_PlaybackUnavailable => Get("Widget_PlaybackUnavailable");

    /// <summary>Visualizer paused by Windows accessibility preferences</summary>
    public static string Widget_VisualizerPaused => Get("Widget_VisualizerPaused");
}
