#!/usr/bin/env python3
"""Manage src/PrettyDesk.Presentation/Resources/Strings.resx (the single source of user-facing text, NFR-11).

  strings.py add KEY "text" ["comment"]   add or replace a string, then regenerate the typed accessor
  strings.py gen                          regenerate Strings.Designer.cs from the .resx
  strings.py check                        exit 1 when Strings.Designer.cs is out of date
"""
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent / "src" / "PrettyDesk.Presentation" / "Resources"
RESX = ROOT / "Strings.resx"
DESIGNER = ROOT / "Strings.Designer.cs"

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<root>
  <resheader name="resmimetype"><value>text/microsoft-resx</value></resheader>
  <resheader name="version"><value>2.0</value></resheader>
  <resheader name="reader"><value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
  <resheader name="writer"><value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
"""


def read():
    if not RESX.exists():
        return {}
    items = {}
    for node in ET.parse(RESX).getroot().findall("data"):
        value = node.find("value")
        comment = node.find("comment")
        items[node.get("name")] = (value.text or "", comment.text if comment is not None else "")
    return items


def esc(text):
    return (text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))


def write(items):
    lines = [HEADER.rstrip("\n")]
    for key in sorted(items):
        value, comment = items[key]
        lines.append(f'  <data name="{key}" xml:space="preserve">')
        lines.append(f"    <value>{esc(value)}</value>")
        if comment:
            lines.append(f"    <comment>{esc(comment)}</comment>")
        lines.append("  </data>")
    lines.append("</root>\n")
    RESX.write_text("\n".join(lines), encoding="utf-8")


def designer_text(items):
    out = [
        "// <auto-generated>Generated by tools/strings.py from Strings.resx. Do not edit.</auto-generated>",
        "#nullable enable",
        "using System.Globalization;",
        "using System.Resources;",
        "",
        "namespace PrettyDesk.Presentation.Resources;",
        "",
        "/// <summary>Typed access to <c>Strings.resx</c>. Every user-facing string lives there (NFR-11).</summary>",
        "public static class Strings",
        "{",
        '    private static readonly ResourceManager Manager = new("PrettyDesk.Presentation.Resources.Strings", typeof(Strings).Assembly);',
        "",
        "    /// <summary>Overrides the culture for tests and previews; null uses the current UI culture.</summary>",
        "    public static CultureInfo? Culture { get; set; }",
        "",
        "    public static string Get(string key) => Manager.GetString(key, Culture) ?? key;",
        "",
        "    public static string Format(string template, params object?[] args) =>",
        "        string.Format(Culture ?? CultureInfo.CurrentUICulture, template, args);",
        "",
        "    /// <summary>Every key in the resource file, for drift checks.</summary>",
        "    public static IReadOnlyList<string> AllKeys { get; } =",
        "    [",
    ]
    for key in sorted(items):
        out.append(f'        "{key}",')
    out.append("    ];")
    for key in sorted(items):
        value, comment = items[key]
        summary = esc(value.replace("\n", " "))
        out.append("")
        out.append(f"    /// <summary>{summary}</summary>")
        out.append(f'    public static string {key} => Get("{key}");')
    out.append("}")
    out.append("")
    return "\n".join(out)


def main(argv):
    if len(argv) < 2:
        print(__doc__)
        return 2
    items = read()
    command = argv[1]
    if command == "add":
        key, value = argv[2], argv[3]
        if not re.fullmatch(r"[A-Z][A-Za-z0-9]*_[A-Za-z0-9_]+", key):
            print(f"Key '{key}' must look like Area_Name")
            return 1
        items[key] = (value, argv[4] if len(argv) > 4 else items.get(key, ("", ""))[1])
        write(items)
        DESIGNER.write_text(designer_text(items), encoding="utf-8")
        return 0
    if command == "gen":
        DESIGNER.write_text(designer_text(items), encoding="utf-8")
        return 0
    if command == "check":
        current = DESIGNER.read_text(encoding="utf-8") if DESIGNER.exists() else ""
        if current != designer_text(items):
            print("Strings.Designer.cs is out of date; run tools/strings.py gen")
            return 1
        return 0
    print(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
